config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :games, only: [:index, :show]
  # resources :images, only: :get
  get 'images/:data' => 'images#show', :as=>:image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.xml
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @games }
    end
  end

  # GET /games/1
  # GET /games/1.xml
  def show
    @game = Game.find(params[:id])
    @homepage = "#{request.protocol}#{request.host_with_port}/"

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @game }
      format.jnlp
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
    # data is 0..65535 - so 8x2 pixels (4 needed for a screen square)
    # could start with 0..255 for simplicity (maybe hex string?)
    @data = params[:data]
    # we can do fg / bg using CSS
    # foreground is 0..7
    # @foreground = params[:foreground]
    # background is 0..7
    # @background = params[:background]
    @image = MiniMagick::Image.new do |image|
      image.draw_point 0, 0
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/games/index.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:tapfile) %></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.name, game_path(game) %></td>
        <td><%= game.tapfile %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/show.html.erb
<!-- $Id$ -->
<div align="center">
  <div class="page-header">
    <b><%= t '.title', :default => @game.name %></b>(<%= @game.tapfile %>)
  </div>

  <dl class="dl-horizontal">
    <dd><%= link_to 'Play Java Version', game_path(@game, format: :jnlp) %>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                games_path, :class => 'btn btn-default'  %>
    </dd>
  </dl>
  <div>
    <%= content_tag :canvas, 'Game', width: 512, height: 384, id: 'applet',
                    class: 'applet', style: "border:1px solid #000000;",
                    data: { load: "#{request.protocol}#{request.host_with_port}/#{@game.tapfile}",
                            rom: "#{request.protocol}#{request.host_with_port}/spectrum.rom" } %>
  </div>
  <!--<canvas id="myCanvas" width="200" height="100"></canvas>-->
  <!--<applet name="qaop" archive="/qaop.jar" code="Qaop" width="320" height="256" alt="Oh dear no applet">-->
  <!--  <param name="load" value="/<%#= @game.tapfile %>"/>-->
  <!--</applet>-->

  <%= image_tag "SpectrumKeyboard.png" %>
</div>

app/views/games/show.jnlp.erb
<?xml version="1.0" encoding="utf-8"?>
<jnlp spec="1.0+" codebase="<%= @homepage %>" href="games/<%= @game.id %>.jnlp">
    <information>
        <title>Qaop Testing</title>
        <vendor>Starswan Systems Ltd</vendor>
        <homepage href="<%= @homepage %>" />
        <description>QAOP JNLP Launcher</description>
    </information>
    <security>
        <sandbox />
    </security>
    <resources>
        <j2se version="1.8+" />
        <jar href="qaop.jar" main="true"/>
    </resources>
    <application-desc name="Qaop" main-class="Qaop">
      <argument><%= @game.tapfile %></argument>
    </application-desc>
</jnlp>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Retroelm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= javascript_pack_tag "hello_elm" %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= javascript_include_tag "hello_elm", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>